{
 "title": "Pre-configured RIoT IS dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "RabbitMQ – queue filling rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kpi-fulfillment-check-requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-requests\"}[1m])",
     "legendFormat": "Per second rate of 'kpi-fulfillment-check-requests' queue filling"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-results\"}[1m])",
     "legendFormat": "Per second rate of 'kpi-fulfillment-check-results' queue filling"
    }
   ]
  },
  {
   "title": "sd-instance-registration-requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"sd-instance-registration-requests\"}[1m])",
     "legendFormat": "Per second rate of 'sd-instance-registration-requests' queue filling"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-requests\"}[1m])",
     "legendFormat": "Per second rate of 'kpi-fulfillment-check-requests' queue filling"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-results\"}[1m])",
     "legendFormat": "Per second rate of 'kpi-fulfillment-check-results' queue filling"
    }
   ]
  },
  {
   "title": "sd-instance-registration-requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages{queue=\"sd-instance-registration-requests\"}[1m])",
     "legendFormat": "Per second rate of 'sd-instance-registration-requests' queue filling"
    }
   ]
  },
  {
   "title": "RabbitMQ – number of messages in queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "kpi-fulfillment-check-requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-requests\"}",
     "legendFormat": "Number of messages in the 'kpi-fulfillment-check-requests' queue"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-results\"}",
     "legendFormat": "Number of messages in the 'kpi-fulfillment-check-results' queue"
    }
   ]
  },
  {
   "title": "sd-instance-registration-requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"sd-instance-registration-requests\"}",
     "legendFormat": "Number of messages in the 'sd-instance-registration-requests' queue"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-requests\"}",
     "legendFormat": "Number of messages in the 'kpi-fulfillment-check-requests' queue"
    }
   ]
  },
  {
   "title": "kpi-fulfillment-check-results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"kpi-fulfillment-check-results\"}",
     "legendFormat": "Number of messages in the 'kpi-fulfillment-check-results' queue"
    }
   ]
  },
  {
   "title": "sd-instance-registration-requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"sd-instance-registration-requests\"}",
     "legendFormat": "Number of messages in the 'sd-instance-registration-requests' queue"
    }
   ]
  },
  {
   "title": "RabbitMQ – connections and channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "Number of RabbitMQ connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "Number of RabbitMQ channels" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "Number of RabbitMQ connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "Number of RabbitMQ channels" }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MQTT message per second rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(mqtt_message_total{topic=\"topic\"}[1m])",
     "legendFormat": "Per second rate of MQTT message publishing onto the 'topic' topic"
    }
   ]
  },
  {
   "title": "MQTT message per second rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "irate(mqtt_message_total{topic=\"topic\"}[1m])",
     "legendFormat": "Per second rate of MQTT message publishing onto the 'topic' topic"
    }
   ]
  }
 ]
}