resources:
  - ../../base

namespace: riot-prod

images:
  - name: riot-frontend
    newTag: 1.0.0
  - name: riot-backend-core
    newTag: 1.0.0
  - name: riot-message-processing-unit
    newTag: 1.0.0
  - name: riot-mqtt-preprocessor
    newTag: 1.0.0
  - name: riot-time-series-store
    newTag: 1.0.0
