apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: riot
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
