apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: riot
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: websocket
