apiVersion: apps/v1
kind: Deployment
metadata:
  name: riot-backend-core
  namespace: riot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot-backend-core
  template:
    metadata:
      labels:
        app: riot-backend-core
    spec:
      containers:
        - name: riot-backend-core
          image: riot-backend-core:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: POSTGRES_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB_NAME)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB_NAME
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672/
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ALLOWED_ORIGINS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
