apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: riot
type: Opaque
data:
  # RabbitMQ
  RABBITMQ_USER: cmlvdA==
  RABBITMQ_PASSWORD: cmlvdHBhc3M=

  # InfluxDB
  INFLUXDB_INIT_ADMIN_TOKEN: RmdwMm96TXhta1luVUJrendMcGt4NnlkT1ZYeVFxRjQtWlBjdEdqdjgteGtpcllQWVIvb0J0cnBBSE1Dcl9qb1lvSk1Pc1pqbDhkamppdXlPeC1NUl9BPQ==
  INFLUXDB_INIT_ORG: amlhcA==
  INFLUXDB_INIT_BUCKET: amlhcC10aW1lLXNlcmllcw==
  INFLUXDB_INIT_MODE: c2V0dXA=
  INFLUXDB_INIT_USERNAME: dXNlcg==
  INFLUXDB_INIT_PASSWORD: cGFzc3dvcmQ=

  # Mqtt
  MQTT_USER: YWRtaW4=
  MQTT_PASSWORD: cGFzc3dvcmQ=

  # Postgres
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB_NAME: cG9zdGdyZXMtZGI=

  # PgAdmin
  PGADMIN_EMAIL: YWRtaW5AcGdhZG1pbi5jb20=
  PGADMIN_PASSWORD: cGFzc3dvcmQ=

  # Grafana
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: cGFzc3dvcmQ=

  # Mosquitto
  MOSQUITTO_CREDENTIALS: admin:$7$101$N+8kumu5a6JMdRNd$X0yiLfnIF/Cpe9qSzXY6H9DjffU+asjuNQTji5W4zZVCqHsXHwmqhPW4ctWG72da5+iFy2bxMVliJvOufLEShg==
