apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password
  namespace: riot
stringData:
  password.txt: |
    YWRtaW46JDckMTAxJE4rOGt1bXU1YTZKTWRSTmQkWDB5aUxmbklGL0NwZTlxU3pYWTZIOURqZmZVK2FzanVOUVRqaTVXNHpaVkNxSHNYSHdtcWhQVzRjdFdHNzJkYTUraUZ5MmJ4TVZsaUp2T3VmTEVTaGc9PQo=
